Create chatrooms; post and delete messages.
DanLauTeo/ChosenOne pull request #17
Opened 2020-09-08 12:58 UTC by TeoReu

2020-09-08 14:42 UTC, chripell approved these changes

2020-09-08 14:42 UTC, chripell commented on server/routes/chat.go
> +	_, err1 := dsClient.Put(ctx, chatroomKey, &cr)
it is more idiomatic to use _, err =

2020-09-08 14:42 UTC, chripell commented on server/routes/chat.go
> +		fmt.Println(err)
Is it OK to continue in case of error?

2020-09-08 14:42 UTC, chripell commented on server/routes/chat.go
> +		log.Printf("Cannot retrieve user from DataStore: %v", err)
I would suggest to return an error to the client as well. You can user defer if you prefer not to do the same code all the time, or simply a helper function.

2020-09-08 14:42 UTC, chripell commented on server/routes/chat.go
> +		fmt.Println(err)
Is it OK to just continue if there is an error?

2020-09-09 08:55 UTC, Omn1 requested changes
When adding and deleting messages in a conversation, you should check that the user belongs to that conversation

2020-09-09 08:55 UTC, Omn1 commented on frontend/app/src/app/_services/chatroom.service.ts
> +  private chatroomsUrl = 'http://localhost:8000/messages';
Don't use hardcoded address. You need to put `apiEndpoint: "127.0.0.1:8000"` into some config

2020-09-09 08:55 UTC, Omn1 commented on frontend/app/src/app/_services/profile.service.ts
> +    this.routeURL = "http://localhost:8000/user/"+id+"/profile-image";
And here

2020-09-09 08:55 UTC, Omn1 commented on server/routes/chat.go
> +	id := userID + " " + requestedUserID
I'd stick with the autogenerated chatroom id (you see how image id's are generated for reference)

2020-09-09 08:55 UTC, Omn1 commented on server/routes/chat.go
> +		log.Printf("Cannot update user: %v", err)
Why are there two `log.Printf`-s inside this `if`? This applies to several `if`-s below as well

2020-09-16 13:31 UTC, closed without merging